### ISSUE TITLE
安装好插件调用指令报错

### ISSUE THREAD

**Issue by zxcxllwh111** [HibiKier/nonebot-plugin-zxpix#1]
name 'asyncio' is not defined. Did you forget to import 'asyncio'

**Comment by HibiKier** [comment]
截图日志看一下

**Comment by HibiKier** [comment]
更新一下

**Comment by zxcxllwh111** [comment]
![image](https://github.com/user-attachments/assets/6fa2ab98-9c08-4551-bda4-6b512a43be4e)

**Comment by HibiKier** [comment]
更新一下，现在zxpix是0.2版本

**Comment by zxcxllwh111** [comment]
好我看看
