### ISSUE TITLE
[Bug] 是否有人提出rank功能无法使用？

### ISSUE THREAD

**Issue by Florenz0707** [HibiKier/nonebot-plugin-zxpix#2]
当我使用rank功能时，终端出现如下报错：
<img width="1192" alt="屏幕截图 2024-11-22 152313" src="https://github.com/user-attachments/assets/59c13056-b054-4331-a29a-e856297c6ef7">
已通过修改pix_star/data_source.py 第92行
star: {pix.star} => star: {pix.total_bookmarks}
解决。

**Comment by HibiKier** [comment]
cd4532356c3d193a71adb03817f815564431326d
